### ISSUE TITLE
Rename uAAL.utils

### ISSUE THREAD

**Issue by amedranogil** [universAAL/utilities#4]
rename uAAL.utils pom coordinates and package .
see:
https://github.com/universAAL/platform/issues/42

**Comment by Alfiva** [comment]
I copied and renamed uAAL.utils as utilities.api in here, in 528db4f . I made a new artifact instead of refactoring because that would be a mess and this way anything that depended on uAAL.utils can continue to compile while I hunt down dependencies.
Before we release 4.0.0 uAAL.utils will have to be removed.

**Comment by Alfiva** [comment]
Samples no longer use uAAL.utils, they now use the new utilities.api. In theory, uAAL.utils could be removed now... (look inside POMs and features as well, not just the folder)

**Comment by cstockloew** [comment]
OK from my side

**Comment by Alfiva** [comment]
Done in bdf8aa7f94c2640fc96550179e53b06fd707c157
